#!/usr/bin/env bash
# Code installs then setup haproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy

# web1 and web2 servers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 17221-web-01 54.173.146.48 check
   server 17221-web-02 100.26.167.35 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
